#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#define EN_PIN    36 //enable (CFG6)
#define PIN_STEP      12
#define PIN_DIRECTION 13

#define PIN_BUTTON_UP          21
#define PIN_BUTTON_DOWN        19
#define PIN_BUTTON_TOOLCHANGE  18
#define PIN_BUTTON_SET_ZERO    5
#define PIN_BUTTON_SET_SPEED    17
#define PIN_BUTTON_GOTO_BOTTOM 16

#define PIN_ENCODER_A_MINUS 14
#define PIN_ENCODER_B_MINUS 27

#define PIN_ICC_DATA 22
#define PIN_ICC_CLOCK 23

#define PIN_SENSOR_END_STOP_TRIGGER    33
#define PIN_SENSOR_TOOL_LENGTH_TRIGGER 25
#define PIN_SENSOR_TOOL_LENGTH_ENABLED  26

#endif // PIN_DEFINITIONS_H