#ifndef PIN_DEFINITIONS_SMD_H
#define PIN_DEFINITIONS_SMD_H

#define PIN_STEP      15
#define PIN_DIRECTION 13

#define PIN_BUTTON_UP          27
#define PIN_BUTTON_DOWN        26
#define PIN_BUTTON_TOOLCHANGE  25
#define PIN_BUTTON_SET_ZERO    32
#define PIN_BUTTON_SET_SPEED   35
#define PIN_BUTTON_GOTO_BOTTOM 34

#define PIN_ENCODER_A_MINUS 14
#define PIN_ENCODER_B_MINUS 12

#define PIN_ICC_DATA 33
#define PIN_ICC_CLOCK 36

#define PIN_SENSOR_END_STOP_TRIGGER    18
#define PIN_SENSOR_TOOL_LENGTH_TRIGGER 19
#define PIN_SENSOR_TOOL_LENGTH_ENABLED 23

#endif // PIN_DEFINITIONS_SMD_H